[Suggestion] Add stubs to process
bioinformatics-lab/camila_sao_paulo_nf pull request #2
Opened 2021-04-06 01:40 UTC by Mxrcon

# Greeting:
Hello @abhi18av, I would like to contribute with this project and aiming on a easier debugging I suggest the development of stubs to all process and a .sh script that creates mock files that can be handled as input for the workflow using the stub_params.yam file

# Pull Request Purpose:
With the purpose of making easier to debug this code I tried to develop stubs to all processes using `touch` and `mkdir ` that can use mock input files to test if the channel and process handling is going right as fast as possible, this will make very easy to check if the syntax and the workflow logic have any issue.

# P-R ending
I'm putting myself on your disposal, fell free to make any question or send my any doubt or critic you have on this pull request page. 

Hope we have a merge!
Regards, Davi

2021-04-06 08:39 UTC, abhi18av requested changes
Thanks @Mxrcon for taking out the time for this PR :)

I appreciate the efforts and I've requested some changes before we more forward.

2021-04-06 08:39 UTC, abhi18av commented on data/mock_data/generate_mock_data.sh
> +touch mock_ref_seq.gbk
Since we're planning to put this inside the `data/mock_data` folder I guess we could avoid using the `mock` in the naming scheme.

Also, please add more files for the same.

```suggestion
touch 001_R1.fastq.gz
touch 001_R2.fastq.gz
touch ref.gbk
touch ref.fasta
```

2021-04-06 08:39 UTC, abhi18av commented on modules/fastqc/fastqc.nf
> +    touch *.html
Please avoid using `*` while using `touch`.  It's better to use the `genomeName` variable which you get from the `fromFilePairs` channel - which passes a tuple of the following form

[`genomeName`, [`genomeName_R1.fastq.gz`, `genomeName_R2.fastq.gz`]]

NOTE: This is the same issue as the `bactopia` stubs.

2021-04-06 08:39 UTC, abhi18av commented on modules/prokka/prokka.nf
> +
I think it might be better to add a `echo` for the main script as well. Just to confirm that the inferred script is of the right format.

For example




```suggestion
prokka --outdir ${genomeName} --prefix $genomeName --cpus ${task.cpus} --proteins {reference} ${bestContig} 
    """

    stub:
    """
    echo " prokka --outdir ${genomeName} --prefix $genomeName --cpus ${task.cpus} --proteins {reference} ${bestContig}"
    mkdir ${genomeName}
    touch ${genomeName}
    
```

2021-04-06 08:39 UTC, abhi18av commented on modules/quast/quast.nf
> +    touch quast_results
I am not quite sure what's the benefit of using `mkdir` and `touch` for the same folder.

`mkdir` creates a folder, whereas `touch` creates a file.

We only wish to create a folder here, therefore it doesn't make sense to create a file of the same name. Maybe you wanted to create a dummy file _within_ the `quast_results` folder?

2021-04-06 08:39 UTC, abhi18av commented on modules/unicycler/unicycler.nf
> +    touch ${genomeName}/${genomeName}.contigs.fasta
Good, this is the ideal usage of `touch`.

2021-04-06 08:39 UTC, abhi18av commented on params/stub_params.yaml
> +gbk-file: "data/mock_data/mock_ref_seq.gbk"
Please add a new line before the end of file.

2021-04-06 11:02 UTC, Mxrcon commented on data/mock_data/generate_mock_data.sh
> +touch mock_ref_seq.gbk
Ok! I'll add some more files and commit your suggestion

2021-04-06 11:03 UTC, Mxrcon commented on modules/fastqc/fastqc.nf
> +    touch *.html
Ok, thats true, I should be more clearer at the stub declaration, I'll add that.

2021-04-06 11:04 UTC, Mxrcon commented on modules/prokka/prokka.nf
> +
@abhi18av Should i add echo for every script that runs a tool inside it?

2021-04-06 11:05 UTC, Mxrcon commented on modules/quast/quast.nf
> +    touch quast_results
yes, i should have used `quast_results/something`

2021-04-06 11:06 UTC, Mxrcon commented on params/stub_params.yaml
> +gbk-file: "data/mock_data/mock_ref_seq.gbk"
ok!

2021-04-07 00:02 UTC, abhi18av requested changes
Good job @Mxrcon , we're definitely closer to the merge.

Could you please run the `stub` version using `-with-tower` and share the tower workflow with me? I'd like to see how the `echo` commands are behaving in the `stub`.

2021-04-07 00:02 UTC, abhi18av commented on data/mock_data/generate_mock_data.sh
> +touch ref03.fasta
Please add a new line :)

2021-04-07 00:02 UTC, abhi18av commented on modules/spades/spades.nf
>      cp ${genomeName}/scaffolds.fasta ${genomeName}_scaffolds.fasta
This needs to be added to the stub as an `echo` as well

2021-04-07 02:58 UTC, Mxrcon commented on data/mock_data/generate_mock_data.sh
> +touch ref03.fasta
ok!

2021-04-07 03:00 UTC, Mxrcon commented on modules/spades/spades.nf
>      cp ${genomeName}/scaffolds.fasta ${genomeName}_scaffolds.fasta
ok! i forgot this one, adding it.

2021-04-07 03:14 UTC, Mxrcon commented
@abhi18av I've just shared the execution with you on tower, the execution name is `cheesy_mayer`

2021-04-07 09:54 UTC, abhi18av approved these changes
Yup, all looks good - thanks a lot @Mxrcon ! 🎉

2021-04-07 09:54 UTC, merged