[Suggestion] README with DAG file
bioinformatics-lab/camila_sao_paulo_nf pull request #3
Opened 2021-04-07 14:09 UTC by Mxrcon

# Poposal
Hello! I'd like to contribute with this project suggesting the enhancement of the  `README ` file, i took some time writing a simple, but clearer that could help new users on the basic usage of this pipeline, 

# Main Topics
I tried to clarify the basic features of this pipeline on the README file, I hope it will be helpful for new users as they could run it with the reading of this file.

#Ending
I'm your disposal, fell free to ask me anything or criticize any changes if you wish to.

Hope we have a merge!
Regards, Davi

2021-04-19 13:47 UTC, abhi18av requested changes
Hey Davi,

This PR looks good, however there are some minor change requests before I can merge this.

2021-04-19 13:47 UTC, abhi18av commented on README.md
> +## Project structure
I think that since the source code is available for everyone, this section isn't needed.

2021-04-19 13:47 UTC, abhi18av commented on README.md
> +
Need to add a local profile as well.

2021-04-19 13:47 UTC, abhi18av commented on README.md
> +```
There's technically no need to download and then run the workflow, anyone can simply do 

```
nextflow run https://github.com/bioinformatics-lab/camila_sao_paulo_nf --reads $READ --gbkFile $GBK --outdir $OUTDIR
```

2021-04-19 21:40 UTC, Mxrcon commented on README.md
> +
ok! added

2021-04-19 21:41 UTC, Mxrcon commented on README.md
> +```
That's true, I'm adding it to the readme

2021-04-19 23:50 UTC, merged

2021-04-20 00:12 UTC, Mxrcon commented
Thank you 😃! 🎉

2021-04-20 01:37 UTC, abhi18av commented
Eu que agradeço @Mxrcon  😊