Config dev
bioinformatics-lab/camila_sao_paulo_nf pull request #4
Opened 2021-04-07 22:32 UTC by Mxrcon

hey i want to create a pul request

2021-04-07 22:40 UTC, Mxrcon commented on conf/azure.config
> +    azr{
```suggestion
    azurebatch {
```

2021-04-19 13:59 UTC, abhi18av requested changes
@Mxrcon , 

It makes sense to merge this PR after https://github.com/bioinformatics-lab/camila_sao_paulo_nf/pull/3

In addition to this, I have left certain suggestions.

For the `conf/base.config` you could follow this pattern here https://github.com/bioinformatics-lab/mtb_mono_inh_nf/blob/a7a4ebcce946ca6f32fffff2b45ba03d5021f8cf/nextflow.config#L37 for each individual process

2021-04-19 13:59 UTC, abhi18av commented on resources/dag.dot
> +p0 -> p1 [label="sra_ch"];
This file needs to be removed.

2021-04-19 21:01 UTC, Mxrcon commented on resources/dag.dot
> +p0 -> p1 [label="sra_ch"];
ok! removing it

2021-04-19 21:29 UTC, Mxrcon commented on resources/dag.dot
> +p0 -> p1 [label="sra_ch"];
@abhi18av I added a local profile without memory and cpu specification, so it will adapt itself to the local settings of each user, for standard i used what was on each process

2021-04-19 23:52 UTC, abhi18av commented on resources/dag.dot
> +p0 -> p1 [label="sra_ch"];
Cool, makes sense 👍

2021-04-19 23:53 UTC, abhi18av commented on nextflow.config
> +    gls {iCncludeConfig 'conf/gcp.config'}
Please fix this typo 😉

2021-04-19 23:53 UTC, abhi18av commented on nextflow.config
> +    local {includeConfig 'conf/local.config'}
Only one of these is needed, you can remove the `local` profile actually.

2021-04-20 00:02 UTC, Mxrcon commented on nextflow.config
> +    local {includeConfig 'conf/local.config'}
ok! I`ll remove it

2021-04-20 00:04 UTC, Mxrcon commented on nextflow.config
> +    gls {iCncludeConfig 'conf/gcp.config'}
ok! Sorry for it!

2021-04-20 00:05 UTC, Mxrcon commented
@abhi18av I`ve requested the review before commiting it, Is it a problem? I`ve just commited it

2021-04-20 01:39 UTC, abhi18av commented
Nope, it looks fine. I'm going to merge it for now and then over the coming week, I'll tweak the PR and ask you for a review.

2021-04-20 01:39 UTC, merged

2021-04-20 01:39 UTC, abhi18av commented
Thanks @Mxrcon !

2021-04-20 01:47 UTC, Mxrcon commented
Thank you too @abhi18av  It's always a pleasure contribute with your work! 😃 I'll be waiting for your review request.